-- MySQL Script generated by MySQL Workbench
-- Tue Feb 28 16:28:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `codigo` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `prontuario` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `etnia` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `altura` FLOAT NULL,
  `peso` FLOAT NULL,
  `turma_codigo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`prontuario`),
  INDEX `fk_aluno_turma1_idx` (`turma_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`turma_codigo`)
    REFERENCES `mydb`.`turma` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `codigo` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `aluno_prontuario` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_disciplina_aluno_idx` (`aluno_prontuario` ASC) VISIBLE,
  CONSTRAINT `fk_disciplina_aluno`
    FOREIGN KEY (`aluno_prontuario`)
    REFERENCES `mydb`.`aluno` (`prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pre_requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pre_requisito` (
  `numero_pre_requisito` VARCHAR(10) NOT NULL,
  `disciplina_codigo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`numero_pre_requisito`, `disciplina_codigo`),
  INDEX `fk_pre_requisito_disciplina1_idx` (`disciplina_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_pre_requisito_disciplina1`
    FOREIGN KEY (`disciplina_codigo`)
    REFERENCES `mydb`.`disciplina` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro_nota` (
  `codigo` VARCHAR(10) NOT NULL,
  `numero_aluno` VARCHAR(45) NOT NULL,
  `nota` FLOAT NULL,
  `turma_codigo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_registro_nota_turma1_idx` (`turma_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_registro_nota_turma1`
    FOREIGN KEY (`turma_codigo`)
    REFERENCES `mydb`.`turma` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
