-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 14:59:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quimica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quimica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quimica` DEFAULT CHARACTER SET utf8 ;
USE `quimica` ;

-- -----------------------------------------------------
-- Table `quimica`.`Elementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimica`.`Elementos` (
  `id` INT NOT NULL,
  `nome_elemento` VARCHAR(50) NULL,
  `simbolo_elemento` VARCHAR(50) NULL,
  `cor_chama` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quimica`.`Combustiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimica`.`Combustiveis` (
  `id` INT NOT NULL,
  `tipo_combustivel` VARCHAR(50) NULL,
  `elemento_1` VARCHAR(50) NULL,
  `elemento_2` VARCHAR(50) NULL,
  `elemento_3` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quimica`.`Combustiveis_has_Elementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimica`.combustivel_elemento (
    id INT PRIMARY KEY,
    combustivel_id INT,
    elemento_id INT,
    FOREIGN KEY (combustivel_id) REFERENCES combustiveis (id),
    FOREIGN KEY (elemento_id) REFERENCES elementos (id)
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama) VALUES
    (1, 'carbono', 'C', 'laranja'),
    (2, 'hidrogênio', 'H', 'azul claro'),
    (3, 'potássio', 'K', 'lilás'),
    (4, 'oxigênio', 'O', 'azul claro'),
    (5, 'metano', 'CH4', 'azul claro'),
    (6, 'etano', 'C2H6', 'azul claro');
    
alter table combustiveis drop elemento_1;
alter table combustiveis drop elemento_2;
alter table combustiveis drop elemento_3;

INSERT INTO combustiveis (id, tipo_combustivel) VALUES
    (1, 'madeira'),
    (2, 'carvão'),
    (3, 'gás natural');	

INSERT INTO combustivel_elemento (id, combustivel_id, elemento_id) VALUES
    (1, 1, 1),
    (2, 1, 2),
    (3, 1, 3),
    (4, 2, 1),
    (5, 2, 2),
    (6, 2, 4),
    (7, 3, 1),
    (8, 3, 2);

select * from combustiveis;
select * from combustivel_elemento;
select * from elementos;
alter table elementos add sublevel1 TEXT;
alter table elementos add sublevel2 TEXT;
alter table elementos add sublevel3 TEXT;
alter table elementos add sublevel4 TEXT;
alter table elementos add sublevel5 TEXT;
alter table elementos add sublevel6 TEXT;
update elementos set sublevel1 = '1s', sublevel2 = '2s', sublevel3 = '2p'
	where nome_elemento = 'carbono';

ALTER TABLE elementos ADD COLUMN eletrons_ultima_camada INT;  
delete from elementos;
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES
(1, 'Hidrogênio', 'H', 'Lilás', '1s', '', '', '', '', '', 1),
(2, 'Hélio', 'He', 'Amarelo', '1s', '', '', '', '', '', 2),
(3, 'Lítio', 'Li', 'Carmim', '1s', '2s', '', '', '', '', 1),
(4, 'Berílio', 'Be', 'Laranja', '1s', '2s', '', '', '', '', 2),
(5, 'Boro', 'B', 'Verde', '1s', '2s', '2p', '', '', '', 3),
(6, 'Carbono', 'C', 'Amarelo', '1s', '2s', '2p', '', '', '', 4),
(7, 'Nitrogênio', 'N', 'Azul', '1s', '2s', '2p', '', '', '', 5),
(8, 'Oxigênio', 'O', 'Azul claro', '1s', '2s', '2p', '', '', '', 6),
(9, 'Flúor', 'F', 'Amarelo esverdeado', '1s', '2s', '2p', '', '', '', 7),
(10, 'Neônio', 'Ne', 'Laranja avermelhado', '1s', '2s', '2p', '', '', '', 8),
(11, 'Sódio', 'Na', 'Amarelo intenso', '1s', '2s', '2p', '3s', '', '', 1),
(12, 'Magnésio', 'Mg', 'Branco brilhante', '1s', '2s', '2p', '3s', '', '', 2),
(13, 'Alumínio', 'Al', 'Laranja', '1s', '2s', '2p', '3s', '3p', '', 3),
(14, 'Silício', 'Si', 'Azul esverdeado', '1s', '2s', '2p', '3s', '3p', '', 4),
(15, 'Fósforo', 'P', 'Verde azulado', '1s', '2s', '2p', '3s', '3p', '', 5),
(16, 'Enxofre', 'S', 'Azul pálido', '1s', '2s', '2p', '3s', '3p', '', 6);
-- Elemento 16: Enxofre
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (16, 'Enxofre', 'S', 'Azul Claro', '1s2', '2s2', '2p6', '3s2', '3p4', '', 6);

-- Elemento 17: Cloro
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (17, 'Cloro', 'Cl', 'Verde Amarelado', '1s2', '2s2', '2p6', '3s2', '3p5', '', 7);

-- Elemento 18: Argônio
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (18, 'Argônio', 'Ar', 'Sem cor', '1s2', '2s2', '2p6', '3s2', '3p6', '', 8);

-- Elemento 19: Potássio
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (19, 'Potássio', 'K', 'Violeta', '1s2', '2s2', '2p6', '3s2', '3p6', '4s1', 1);

-- Elemento 20: Cálcio
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (20, 'Cálcio', 'Ca', 'Laranja Vermelho', '1s2', '2s2', '2p6', '3s2', '3p6', '4s2', 2);

-- Elemento 21: Escândio
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (21, 'Escândio', 'Sc', 'Sem cor', '1s2', '2s2', '2p6', '3s2', '3p6', '3d1 4s2', 1);

-- Titânio
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (22, 'Titânio', 'Ti', NULL, '1s2', '2s2', '2p6', '3s2', '3p6', '4s2 3d2', 4);

-- Vanádio
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (23, 'Vanádio', 'V', NULL, '1s2', '2s2', '2p6', '3s2', '3p6', '4s2 3d3', 5);

-- Cromo
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (24, 'Cromo', 'Cr', NULL, '1s2', '2s2', '2p6', '3s2', '3p6', '4s1 3d5', 6);

-- Manganês
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (25, 'Manganês', 'Mn', NULL, '1s2', '2s2', '2p6', '3s2', '3p6', '4s2 3d5', 7);

-- Ferro
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (26, 'Ferro', 'Fe', NULL, '1s2', '2s2', '2p6', '3s2', '3p6', '4s2 3d6', 8);

-- Cobalto
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (27, 'Cobalto', 'Co', NULL, '1s2', '2s2', '2p6', '3s2', '3p6', '4s2 3d7', 9);

-- Níquel
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (28, 'Níquel', 'Ni', NULL, '1s2', '2s2', '2p6', '3s2', '3p6', '4s2 3d8', 10);

-- Cobre
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (29, 'Cobre', 'Cu', 'azul', '1s2', '2s2', '2p6', '3s2', '3p6', '4s1 3d10', 11);

-- Zinco
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (30, 'Zinco', 'Zn', 'verde', '1s2', '2s2', '2p6', '3s2', '3p6', '4s2 3d10', 12);

-- Gálio
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (31, 'Gálio', 'Ga', NULL, '1s2', '2s2', '2p6', '3s2', '3p6', '4s2 3d10 4p1', 13);

-- Germânio
INSERT INTO elementos (id, nome_elemento, simbolo_elemento, cor_chama, sublevel1, sublevel2, sublevel3, sublevel4, sublevel5, sublevel6, eletrons_ultima_camada)
VALUES (32, 'Germânio', 'Ge', NULL, '1s2', '2s2', '2p6', '3s2', '3p6', '4s2 3d10 4p2', 14);


select * from elementos;

select c.id,tipo_combustivel, nome_elemento,cor_chama 
	from combustiveis c inner join 
		combustivel_elemento  ce 
			on c.id = ce.combustivel_id 
						inner join
		elementos e 
            on ce.elemento_id = e.id; 
    

SELECT c.tipo_combustivel, GROUP_CONCAT(e.cor_chama SEPARATOR ' + ') AS mistura_cores
FROM combustiveis c
INNER JOIN combustivel_elemento ce ON c.id = ce.combustivel_id
INNER JOIN elementos e ON ce.elemento_id = e.id
GROUP BY c.tipo_combustivel;
