-- MySQL Script generated by MySQL Workbench
-- Tue Feb 14 17:06:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `prontuario` VARCHAR(15) NOT NULL,
  `nome` TEXT(150) NOT NULL,
  `data_nascimento` DATE NULL,
  `genero` CHAR(1) NOT NULL DEFAULT 'N',
  `etnia` VARCHAR(45) NULL DEFAULT 'NÃO INFORMADO',
  `altura` FLOAT NULL DEFAULT 0,
  `peso` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`prontuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `codigo` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `Aluno_prontuario` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_disciplina_Aluno_idx` (`Aluno_prontuario` ASC) ,
  CONSTRAINT `fk_disciplina_Aluno`
    FOREIGN KEY (`Aluno_prontuario`)
    REFERENCES `mydb`.`Aluno` (`prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `codigo` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `semestre` TINYINT(30) NOT NULL,
  `ano` YEAR(4) NOT NULL,
  `professor` VARCHAR(100) NOT NULL,
  `Aluno_prontuario` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_turma_Aluno1_idx` (`Aluno_prontuario` ASC) ,
  CONSTRAINT `fk_turma_Aluno1`
    FOREIGN KEY (`Aluno_prontuario`)
    REFERENCES `mydb`.`Aluno` (`prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro_nota` (
  `codigo` VARCHAR(15) NOT NULL,
  `numero_aluno` VARCHAR(45) NULL,
  `identificador_turma` VARCHAR(45) NULL,
  `nota` FLOAT NOT NULL,
  `turma_codigo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_registro_nota_turma1_idx` (`turma_codigo` ASC) ,
  CONSTRAINT `fk_registro_nota_turma1`
    FOREIGN KEY (`turma_codigo`)
    REFERENCES `mydb`.`turma` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pre_requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pre_requisito` (
  `numero_prerequisito` INT NOT NULL,
  `numero_disciplina` VARCHAR(45) NOT NULL,
  `disciplina_codigo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`numero_prerequisito`, `numero_disciplina`),
  INDEX `fk_pre_requisito_disciplina1_idx` (`disciplina_codigo` ASC) ,
  CONSTRAINT `fk_pre_requisito_disciplina1`
    FOREIGN KEY (`disciplina_codigo`)
    REFERENCES `mydb`.`disciplina` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
